### ISSUE TITLE
Preencher a tag 'teamName' com o nome do time, caso esteja em branco

### ISSUE THREAD

**Issue by xaxaah** [danilovsilva/xaxanalytics_parser#13]
Nos casos onde a demo não possui times setados, o awpy não atribui o teamName para os jogadores automaticamente.

Há a lista lstats, que contém as informações player a player, nesta lista há a tag 'teamName'.
```json
{
  // ...,
  "teamName": ""
  // ...
}
```
Preencher esta tag, de acordo com os jogadores de cada time, com 'Team 1' para o time vencedor e 'Team 2' para o perdedor.

**Comment by danilovsilva** [comment]
@xaxaah pode revisar a solução aplicada para o teamName?

**Comment by danilovsilva** [comment]
Rolling back the modification as @xaxaah said it was already done!
